// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRUJILLOISAAC_EXAMENP1.Data;

#nullable disable

namespace TRUJILLOISAAC_EXAMENP1.Migrations
{
    [DbContext(typeof(TRUJILLOISAAC_EXAMENP1Context))]
    [Migration("20241028130621_MiPrimeraMigracion")]
    partial class MiPrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TRUJILLOISAAC_EXAMENP1.Models.Celular", b =>
                {
                    b.Property<int>("Idceluar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idceluar"));

                    b.Property<int>("año")
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("Idceluar");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("TRUJILLOISAAC_EXAMENP1.Models.ITrujillo", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Idceluar")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("numfav")
                        .HasColumnType("float");

                    b.Property<bool>("quierecambiar")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario");

                    b.ToTable("ITrujillo");
                });
#pragma warning restore 612, 618
        }
    }
}
